name: Cosmos DB CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install azure-cosmos

    - name: Set up environment variables
      run: |
        echo "HOST=${{ secrets.ACCOUNT_HOST }}" >> $GITHUB_ENV
        echo "MASTER_KEY=${{ secrets.ACCOUNT_KEY }}" >> $GITHUB_ENV

    - name: Run script
      run: python run.py
