name: Trigger auto deployment for earlent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ dev ]
    paths:
    - '**'
    - '.github/workflows/earlent-AutoDeployTrigger-63bcd090-148d-46b7-b34b-2cb4b1971f2a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EARLENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EARLENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EARLENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: earlent.azurecr.io
          registryUsername: ${{ secrets.EARLENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EARLENT_REGISTRY_PASSWORD }}
          containerAppName: earlent
          resourceGroup: mental_health_companion
          imageToBuild: earlent.azurecr.io/earlent:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


