name: Build and deploy Node.js app to Azure Web App - mental-health-app-web

# Run the workflow on pushes to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./client/
        
        steps:
            - name: Checkout Git repository
              uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
                
            - name: Install dependencies
              run: npm install
        
            - name: Build distribution files
              run: npm run build
              env: 
                VITE_AXIOS_BASE_URL: ${{ env.VITE_AXIOS_BASE_URL }}
            
            - name: Upload artifact for deploment job
              uses: actions/upload-artifact@v4
              with:
                name: node-app
                path: ./client/dist/

    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'production'
        url: ${{ env.WEB_APP_URL }}
      
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: node-app
        
        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: mental-health-app-web
            slot-name: 'Production'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: .