name: Python CI

on:
    push:
      paths:
      - "server/**"
      branches:
          - dev
    
    pull_request:
      paths:
      - "server/**"

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug
      run: |
        pwd
        ls -l ./server

        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest ./server/tests/


  lint_with_black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-black@v1


  security_check:
    name: Run security checks with Bandit
    runs-on: ubuntu-latest
    steps:
      - uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: high
          confidence: high
          exit_zero: true